//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phoodchef.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class phoodbEntities : DbContext
    {
        public phoodbEntities()
            : base("name=phoodbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<enduser> endusers { get; set; }
        public virtual DbSet<ingredient> ingredients { get; set; }
        public virtual DbSet<library> libraries { get; set; }
        public virtual DbSet<recIngred> recIngreds { get; set; }
        public virtual DbSet<recipe> recipes { get; set; }
        public virtual DbSet<recRate> recRates { get; set; }
        public virtual DbSet<userIngred> userIngreds { get; set; }
        public virtual DbSet<utensil> utensils { get; set; }
    }
}
