//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phoodchef.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recIngred
    {
        public int RecId { get; set; }
        public int IngredId { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Unit { get; set; }
        public string IngredRole { get; set; }
        public Nullable<int> IngredRec { get; set; }
        public Nullable<int> SubFor { get; set; }
    
        public virtual ingredient ingredient { get; set; }
        public virtual recipe recipe { get; set; }
    }
}
