//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phoodchef.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipe()
        {
            this.recIngreds = new HashSet<recIngred>();
            this.recRates = new HashSet<recRate>();
            this.categories = new HashSet<category>();
            this.libraries = new HashSet<library>();
            this.utensils = new HashSet<utensil>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> cookTime { get; set; }
        public string cookunit { get; set; }
        public string instructions { get; set; }
        public string yield { get; set; }
        public Nullable<int> serveMin { get; set; }
        public Nullable<int> serveMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recIngred> recIngreds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recRate> recRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<category> categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<library> libraries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<utensil> utensils { get; set; }
    }
}
