//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phoodchef.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userIngred
    {
        public int UserId { get; set; }
        public int IngredId { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Unit { get; set; }
    
        public virtual enduser enduser { get; set; }
        public virtual ingredient ingredient { get; set; }
    }
}
